# Generated by Django 5.0.3 on 2024-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
