# Generated by Django 5.0.3 on 2024-05-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
