# Generated by Django 5.0.3 on 2024-03-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('ep', 'EP'), ('album', 'Album')], max_length=30)),
                ('release', models.DateField()),
                ('description', models.CharField(max_length=400)),
                ('gender', models.CharField(choices=[('vaporwave', 'Vaporwave'), ('rock', 'Rock'), ('lo-fi', 'Lo-fi'), ('synthwave', 'Synthwave'), ('mallsoft', 'Mallsoft')], max_length=30)),
                ('artits', models.ManyToManyField(to='artist.artist')),
            ],
        ),
    ]
