# Generated by Django 5.0.3 on 2024-03-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('release', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('numberoftrack', models.IntegerField()),
                ('track', models.CharField(max_length=50)),
                ('artits', models.ManyToManyField(to='artist.artist')),
            ],
        ),
    ]
