# Generated by Django 5.0.3 on 2024-04-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='albums/')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('type', models.CharField(choices=[('ep', 'EP'), ('album', 'Album')], max_length=30)),
                ('release', models.DateField()),
                ('description', models.CharField(max_length=400)),
                ('gender', models.CharField(choices=[('vaporwave', 'Vaporwave'), ('rock', 'Rock'), ('lo-fi', 'Lo-fi'), ('synthwave', 'Synthwave'), ('mallsoft', 'Mallsoft')], max_length=30)),
                ('artist', models.ManyToManyField(to='artist.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('stars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='album.album')),
            ],
        ),
    ]
