# Generated by Django 5.0.3 on 2024-04-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='gender',
        ),
        migrations.AddField(
            model_name='album',
            name='genders',
            field=models.ManyToManyField(related_name='albums', to='gender.gender'),
        ),
    ]
