# Generated by Django 5.0.3 on 2024-05-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='music',
        ),
    ]
