# Generated by Django 5.0.3 on 2024-04-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
