# Generated by Django 5.0.3 on 2024-04-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_artist'),
        ('album', '0002_alter_album_gender'),
    ]

    operations = [
    ]
