# Generated by Django 5.0.3 on 2024-05-16 13:13

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_remove_album_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='musica',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
