# Generated by Django 5.0.3 on 2024-05-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_musica'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='musica',
            new_name='nome',
        ),
    ]
