# Generated by Django 5.0.3 on 2024-05-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_rename_musica_album_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='nome',
            new_name='music_name',
        ),
    ]
