# Generated by Django 5.0.3 on 2024-05-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_rename_nome_album_music_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='music_name',
            new_name='music_info',
        ),
    ]
