# Generated by Django 5.0.3 on 2024-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist',
            field=models.ManyToManyField(related_name='albums', to='artist.artist'),
        ),
    ]
